[package]
name = "layout2d"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
rctree = { git = "https://github.com/SimonSapin/rust-forest" }
simd = "0.2.0"

[dev-dependencies]
rand = "0.3.15"