[package]
name = "explorer"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
glium = "*"
rctree = { git = "https://github.com/SimonSapin/rust-forest" }
lazy_static = "0.2"
simd = "0.2.0"
rusttype = "0.2.1"

[profile.release]
lto = true
panic = 'abort'