[package]
name = "explorer"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
glium = "*"
cgmath = { version = "0.14.1", features = ["use_simd"] }
rctree = { git = "https://github.com/SimonSapin/rust-forest" }
lazy_static = "0.2"
